server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test # jdbc:mariadb://localhost:3306/test  #${DATABASE_URL}?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: false
  output:
    ansi:
      enabled: always
  thymeleaf:
    enabled: true                  # Thymeleaf 활성화 여부
    prefix: classpath:/templates/view/  # 템플릿 경로
    suffix: .html                  # 템플릿 파일 확장자
    mode: HTML                     # 템플릿 처리 모드
    encoding: UTF-8                # 템플릿 파일 인코딩
    cache: false                   # 캐싱 비활성화 (개발 환경)
    servlet:
      content-type: text/html      # 응답 Content-Type 설정

logging:
  level:
    '[com.example.kakao]': DEBUG
    '[org.hibernate.type]': TRACE

file:
  path: ./images/

springdoc:
  swagger-ui:
    path: /api/docs  # Swagger UI 경로를 '/api-docs'로 변경
